# Basic Calculations to Explore New Priority Calculation

In [3]:
import numpy as np
import prioritycalcs.basics.eigen as eigen

AttributeError: 'module' object has no attribute 'harker_fix'

## Standard Eigenvector Calculation

In [2]:
def harker_fix(mat):
    nrows = mat.shape[0]
    ncols = mat.shape[1]
    rval = mat.copy()
    for row in range(nrows):
        val = 1
        for col in range(ncols):
            if col != row and mat[row,col]==0:
                val+=1
        rval[row,row]=val
    return(rval)

In [70]:
def largest_eigen(mat, error = 1e-10, use_harker = False):
    if use_harker:
        mat = harker_fix(mat)
    size = mat.shape[0]
    vec = np.ones([size])
    diff = 1
    while diff > error:
        nextv = np.matmul(mat, vec)
        nextv = nextv/sum(nextv)
        diff = max(abs(nextv - vec))
        vec = nextv
    return(vec)

## Standard geometric average calculation

In [113]:
def geom_avg(vals):
    rval=1.0
    count = 0
    for val in vals:
        val = vals[count]
        if val != 0:
            rval *= val
            count+=1
    if count != 0:
        rval = pow(rval, 1.0/count)
    return(rval)

def geom_avg_mat(mat, coeffs = None):
    size = mat.shape[0]
    rval = np.ones([size])
    for row in range(size):
        if np.any(coeffs):
            theRow = mat[row,:] * np.array(coeffs)
        else:
            theRow = mat[row,:]
        rval[row] = geom_avg(theRow)
    return(rval)

## The new geometric average calculation

In [119]:
def be_priorities(mat, error = 1e-10):
    size = mat.shape[0]
    vec = np.ones([size])
    diff = 1
    count=0
    while diff >= error and count < 100:
        nextv = geom_avg_mat(mat, vec)
        #nextv = nextv/max(nextv)
        diff = max(abs(nextv - vec))
        vec = nextv
        count+=1
    return(vec/sum(vec))

In [120]:
n=np.array([[1, 2.],[1./2, 1]])
geom_avg_mat(n)

array([ 1.41421356,  0.70710678])

In [121]:
be_priorities(n)

array([ 0.66666667,  0.33333333])

In [122]:
w = np.array([[1, 2, 6], [1./2, 1,0 ], [1./6,0, 1]])
be_priorities(w)

array([ 0.6,  0.3,  0.1])

In [123]:
largest_eigen(harker_fix(w))

array([ 0.6,  0.3,  0.1])

In [124]:
z=be_priorities(w)
z

array([ 0.6,  0.3,  0.1])

In [125]:
w

array([[ 1.        ,  2.        ,  6.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.16666667,  0.        ,  1.        ]])

In [126]:
np.array([1,2])*np.array([3,7])

array([ 3, 14])