# Examples comparing eigen to new calc

In [1]:
import numpy as np
import prioritycalcs.basics.eigen as eigen
import prioritycalcs.basics.bill as bill
import scipy.stats as ss
%precision 3

'%.3f'

In [2]:
sarah = np.array([[1.,  1./3, 3. , 1], 
                  [3 ,   1., 1./3 ,3 ], 
                  [1./3 , 3, 1., 1./9], 
                  [1, 1./3, 9, 1.]])
sarah

array([[ 1.   ,  0.333,  3.   ,  1.   ],
       [ 3.   ,  1.   ,  0.333,  3.   ],
       [ 0.333,  3.   ,  1.   ,  0.111],
       [ 1.   ,  0.333,  9.   ,  1.   ]])

## Comparing Eigen To Bill's Method

In [3]:
print(eigen.largest_eigen(sarah))
print(bill.be_priorities(sarah))

[ 0.179  0.297  0.18   0.345]
[ 0.238  0.313  0.137  0.313]


## Quick sanity check that both calcs agree on 3x3 submatrices of those votes

In [4]:
indices = [0,2,3]
subsarah = sarah[indices,:][:,indices]
print(eigen.largest_eigen(subsarah))
print(bill.be_priorities(subsarah))

[ 0.374  0.086  0.539]
[ 0.374  0.086  0.539]


## An example for Elena
This is an example that Elena is going to do

In [5]:
elena = np.array([
        [1, 2, 3, 4],
        [1./2, 1, 5, 6],
        [1./3, 1./5, 1, 7],
        [1./4, 1./6, 1./7, 1]
    ])
print(elena)

[[ 1.     2.     3.     4.   ]
 [ 0.5    1.     5.     6.   ]
 [ 0.333  0.2    1.     7.   ]
 [ 0.25   0.167  0.143  1.   ]]


In [24]:
print(eigen.largest_eigen(elena))
print(bill.be_priorities(elena))
print(eigen.inconsistency(elena))

[ 0.408  0.376  0.163  0.053]
[ 0.419  0.372  0.156  0.053]
0.206964932923


We are not particularly inconsistent, so the results are fairly similar.

## Another example with more inconsistency

In [7]:
elena2 = np.array([
        [1, 2, 1./9, 4],
        [1./2, 1, 5, 6],
        [9, 1./5, 1, 7],
        [1./4, 1./6, 1./7, 1]
    ])
elena2

array([[ 1.   ,  2.   ,  0.111,  4.   ],
       [ 0.5  ,  1.   ,  5.   ,  6.   ],
       [ 9.   ,  0.2  ,  1.   ,  7.   ],
       [ 0.25 ,  0.167,  0.143,  1.   ]])

In [23]:
print(eigen.largest_eigen(elena2))
print(bill.be_priorities(elena2))
print(eigen.inconsistency(elena2))

[ 0.186  0.408  0.374  0.032]
[ 0.19   0.386  0.369  0.054]
0.846985122921


## Minimal working example

In [9]:
mwe = np.array([
        [1, 2, 1/2., 1],
        [1/2., 1, 1, 1],
        [2., 1, 1, 1],
        [1, 1, 1, 1]
    ])
print(mwe)

[[ 1.   2.   0.5  1. ]
 [ 0.5  1.   1.   1. ]
 [ 2.   1.   1.   1. ]
 [ 1.   1.   1.   1. ]]


In [10]:
print(eigen.largest_eigen(mwe))
print(eigen.largest_eigen(mwe.transpose()))
print(ss.rankdata(eigen.largest_eigen(mwe)))
print(ss.rankdata(eigen.largest_eigen(mwe.transpose())))

[ 0.253  0.209  0.299  0.239]
[ 0.253  0.299  0.209  0.239]
[ 3.  1.  4.  2.]
[ 3.  4.  1.  2.]


In [11]:
print(eigen.inconsistency(mwe))
print(eigen.inconsistency(mwe.transpose()))

0.068710207503
0.068710207503


In [12]:
print(bill.be_priorities(mwe))
print(bill.be_priorities(mwe.transpose()))
print(ss.rankdata(bill.be_priorities(mwe)))
print(ss.rankdata(bill.be_priorities(mwe.transpose())))

[ 0.248  0.209  0.295  0.248]
[ 0.248  0.295  0.209  0.248]
[ 2.5  1.   4.   2.5]
[ 2.5  4.   1.   2.5]


## Slightly less minimal working example

In [13]:
mwe2 = np.array([
        [1, 2, 1/2., 1/1.1],
        [1/2., 1, 1, 1],
        [2., 1, 1, 1],
        [1.1, 1, 1, 1]
    ])
mwe2

array([[ 1.   ,  2.   ,  0.5  ,  0.909],
       [ 0.5  ,  1.   ,  1.   ,  1.   ],
       [ 2.   ,  1.   ,  1.   ,  1.   ],
       [ 1.1  ,  1.   ,  1.   ,  1.   ]])

In [14]:
print(eigen.largest_eigen(mwe2))
print(eigen.largest_eigen(mwe2.transpose()))
print(ss.rankdata(eigen.largest_eigen(mwe2)))
print(ss.rankdata(eigen.largest_eigen(mwe2.transpose())))

[ 0.248  0.209  0.298  0.245]
[ 0.258  0.301  0.208  0.233]
[ 3.  1.  4.  2.]
[ 3.  4.  1.  2.]


In [15]:
print(bill.be_priorities(mwe2))
print(bill.be_priorities(mwe2.transpose()))
print(ss.rankdata(bill.be_priorities(mwe2)))
print(ss.rankdata(bill.be_priorities(mwe2.transpose())))

[ 0.242  0.209  0.295  0.254]
[ 0.254  0.295  0.209  0.242]
[ 2.  1.  4.  3.]
[ 3.  4.  1.  2.]


In [16]:
def bnorm(x):
    return(x/sum(x))

def binv(x):
    return(bnorm(1./x))

In [17]:
eigen.inconsistency(mwe2)

0.069

## Calculations from ISAHP Paper

In [27]:
#First define the calculation on a general matrix
def details_3_cmps(sarah):
    print(eigen.largest_eigen(sarah))
    print(binv(eigen.largest_eigen(sarah)))
    print(eigen.largest_eigen(sarah.transpose()))
    print()
    print(bill.be_priorities(sarah))
    print(binv(bill.be_priorities(sarah)))
    print(bill.be_priorities(sarah.transpose()))
    print()
    print(bill.b_priorities2(sarah))
    print(binv(bill.b_priorities2(sarah)))
    print(bill.b_priorities2(sarah.transpose()))
    print()
    print(eigen.inconsistency(sarah))

In [28]:
details_3_cmps(sarah)

[ 0.179  0.297  0.18   0.345]
[ 0.321  0.193  0.319  0.166]
[ 0.187  0.24   0.4    0.173]

[ 0.238  0.313  0.137  0.313]
[ 0.235  0.179  0.407  0.179]
[ 0.235  0.179  0.407  0.179]

[ 0.212  0.358  0.174  0.256]
[ 0.275  0.162  0.335  0.227]
[ 0.232  0.253  0.359  0.156]

0.924724652579


In [29]:
details_3_cmps(elena)

[ 0.408  0.376  0.163  0.053]
[ 0.081  0.088  0.203  0.628]
[ 0.076  0.084  0.207  0.634]

[ 0.419  0.372  0.156  0.053]
[ 0.078  0.088  0.21   0.624]
[ 0.078  0.088  0.21   0.624]

[ 0.492  0.31   0.127  0.071]
[ 0.075  0.118  0.289  0.518]
[ 0.117  0.097  0.134  0.651]

0.206964932923


In [30]:
details_3_cmps(mwe)

[ 0.253  0.209  0.299  0.239]
[ 0.243  0.295  0.205  0.257]
[ 0.253  0.299  0.209  0.239]

[ 0.248  0.209  0.295  0.248]
[ 0.248  0.295  0.209  0.248]
[ 0.248  0.295  0.209  0.248]

[ 0.238  0.214  0.297  0.252]
[ 0.259  0.289  0.208  0.245]
[ 0.238  0.297  0.214  0.252]

0.068710207503
