# Examples comparing eigen to new calc

In [1]:
import numpy as np
import prioritycalcs.basics.eigen as eigen
import prioritycalcs.basics.bill as bill

In [2]:
sarah = np.array([[1.,  1./3, 3. , 1], 
                  [3 ,   1., 1./3 ,3 ], 
                  [1./3 , 3, 1., 1./9], 
                  [1, 1./3, 9, 1.]])
sarah

array([[ 1.        ,  0.33333333,  3.        ,  1.        ],
       [ 3.        ,  1.        ,  0.33333333,  3.        ],
       [ 0.33333333,  3.        ,  1.        ,  0.11111111],
       [ 1.        ,  0.33333333,  9.        ,  1.        ]])

## Comparing Eigen To Bill's Method

In [11]:
print(eigen.largest_eigen(sarah))
print(bill.be_priorities(sarah))

[ 0.17880868  0.29666914  0.17972795  0.34479423]
[ 0.237558    0.31264391  0.13715418  0.31264391]


## Quick sanity check that both calcs agree on 3x3 submatrices of those votes

In [55]:
indices = [0,2,3]
subsarah = sarah[indices,:][:,indices]
print(eigen.largest_eigen(subsarah))
print(bill.be_priorities(subsarah))

[ 0.37405971  0.08645284  0.53948745]
[ 0.37405971  0.08645284  0.53948745]
