# Example that led to this investigation

In [1]:
import numpy as np
import prioritycalcs.basics.eigen as eigen
import prioritycalcs.basics.bill as bill

## The original person's votes (Sarah)

In [4]:
sarah = np.array([[1.,  1./3, 3. , 1], 
                  [3 ,   1., 1./3 ,3 ], 
                  [1./3 , 3, 1., 1./9], 
                  [1, 1./3, 9, 1.]])
sarah

array([[ 1.        ,  0.33333333,  3.        ,  1.        ],
       [ 3.        ,  1.        ,  0.33333333,  3.        ],
       [ 0.33333333,  3.        ,  1.        ,  0.11111111],
       [ 1.        ,  0.33333333,  9.        ,  1.        ]])

## Sarah's doppleganger's votes

In [6]:
sarah_dopple = sarah.transpose()
sarah_dopple

array([[ 1.        ,  3.        ,  0.33333333,  1.        ],
       [ 0.33333333,  1.        ,  3.        ,  0.33333333],
       [ 3.        ,  0.33333333,  1.        ,  9.        ],
       [ 1.        ,  3.        ,  0.11111111,  1.        ]])

## Sarah's priorities and her doppleganger using eigenvector method

In [7]:
eigen.largest_eigen(sarah)

array([ 0.17880868,  0.29666914,  0.17972795,  0.34479423])

In [8]:
eigen.largest_eigen(sarah_dopple)

array([ 0.1867996 ,  0.24011723,  0.39996439,  0.17311878])

# Trying to make a slightly less inconsistent example

### Example 1.

In [10]:
ex1 = np.array([
        [1, 2, 1, 1],
        [1./2, 1, 2, 5],
        [1 , 1./2, 1, 4],
        [1, 1./5 , 1./4, 1]
    ])
ex1

array([[ 1.  ,  2.  ,  1.  ,  1.  ],
       [ 0.5 ,  1.  ,  2.  ,  5.  ],
       [ 1.  ,  0.5 ,  1.  ,  4.  ],
       [ 1.  ,  0.2 ,  0.25,  1.  ]])

In [11]:
eigen.largest_eigen(ex1)

array([ 0.28947169,  0.33999829,  0.25449746,  0.11603256])

Ranking is (2, 1, 3, 4)

In [12]:
eigen.largest_eigen(ex1.transpose())

array([ 0.19880876,  0.159382  ,  0.17478851,  0.46702073])

Ranking is (2, 4, 3, 1)

### Example 2.

In [24]:
ex2 = np.array([
        [1, 2, 1, 1./3],
        [1./2, 1, 2, 3],
        [1 , 1./2, 1, 4],
        [3, 1./3 , 1./4, 1]
    ])
ex2

array([[ 1.        ,  2.        ,  1.        ,  0.33333333],
       [ 0.5       ,  1.        ,  2.        ,  3.        ],
       [ 1.        ,  0.5       ,  1.        ,  4.        ],
       [ 3.        ,  0.33333333,  0.25      ,  1.        ]])

In [25]:
eigen.largest_eigen(ex2)

array([ 0.22363666,  0.29973146,  0.27744299,  0.19918889])

Ranking (3, 1, 2, 4)

In [26]:
eigen.largest_eigen(ex2.transpose())

array([ 0.29989653,  0.18967094,  0.18058288,  0.32984964])

Ranking (2, 3, 4, 1)

### Example 3.

In [47]:
ex3 = np.array([
        [1, 2, 2, 1./2],
        [1./2, 1, 2, 1],
        [1./2 , 1./2, 1, 3],
        [2, 1, 1./3, 1]
    ])
ex3

array([[ 1.        ,  2.        ,  2.        ,  0.5       ],
       [ 0.5       ,  1.        ,  2.        ,  1.        ],
       [ 0.5       ,  0.5       ,  1.        ,  3.        ],
       [ 2.        ,  1.        ,  0.33333333,  1.        ]])

In [48]:
eigen.largest_eigen(ex3)

array([ 0.28464746,  0.23109171,  0.25156613,  0.23269469])

Ranking (1, 4, 2, 3)

In [46]:
eigen.largest_eigen(ex3.transpose())

array([ 0.21884099,  0.22680592,  0.2603409 ,  0.2940122 ])

Ranking (4, 3, 2, 1)