# Basic Calculations to Explore New Priority Calculation

In [1]:
import numpy as np
import prioritycalcs.basics.eigen as eigen
import prioritycalcs.basics.bill as bill

In [2]:
n=np.array([[1, 2.],[1./2, 1]])
bill.geom_avg_mat(n)

array([ 1.41421356,  0.70710678])

In [3]:
bill.be_priorities(n)

array([ 0.66666667,  0.33333333])

In [4]:
w = np.array([[1, 2, 6], [1./2, 1,0 ], [1./6,0, 1]])
bill.be_priorities(w)

array([ 0.6,  0.3,  0.1])

In [5]:
eigen.largest_eigen(eigen.harker_fix(w))

array([ 0.6,  0.3,  0.1])

In [6]:
z=bill.be_priorities(w)
z

array([ 0.6,  0.3,  0.1])

In [7]:
w

array([[ 1.        ,  2.        ,  6.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.16666667,  0.        ,  1.        ]])

In [8]:
np.array([1,2])*np.array([3,7])

array([ 3, 14])

In [9]:
bill.b_priorities2(w)

array([ 0.63356681,  0.27341388,  0.09301931])

In [10]:
v = w.copy()
v

array([[ 1.        ,  2.        ,  6.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.16666667,  0.        ,  1.        ]])

In [11]:
v[1,2]=3
v[2,1]=1./3

In [12]:
v

array([[ 1.        ,  2.        ,  6.        ],
       [ 0.5       ,  1.        ,  3.        ],
       [ 0.16666667,  0.33333333,  1.        ]])

In [13]:
bill.b_priorities2(v)

array([ 0.6,  0.3,  0.1])

In [14]:
eigen.largest_eigen(w)

array([ 0.67962276,  0.24028293,  0.08009431])