# Basic Calculations to Explore New Priority Calculation

In [1]:
import numpy as np
import prioritycalcs.basics.eigen as eigen
import prioritycalcs.basics.bill as bill

In [3]:
n=np.array([[1, 2.],[1./2, 1]])
bill.geom_avg_mat(n)

array([ 1.41421356,  0.70710678])

In [4]:
bill.be_priorities(n)

array([ 0.66666667,  0.33333333])

In [5]:
w = np.array([[1, 2, 6], [1./2, 1,0 ], [1./6,0, 1]])
bill.be_priorities(w)

array([ 0.6,  0.3,  0.1])

In [7]:
eigen.largest_eigen(eigen.harker_fix(w))

array([ 0.6,  0.3,  0.1])

In [9]:
z=bill.be_priorities(w)
z

array([ 0.6,  0.3,  0.1])

In [125]:
w

array([[ 1.        ,  2.        ,  6.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.16666667,  0.        ,  1.        ]])

In [126]:
np.array([1,2])*np.array([3,7])

array([ 3, 14])